@Library('pipeline-library')

Map tasks = [failFast: false]

configuration = ["checkout", "download_tooling"]

tasks['x86'] = { ->
    node {
        multiArchFlow('x86')
    }
}
tasks['arm'] = { ->
    node {
        multiArchFlow('arm')
    }
}

// Run both task in parallel
parallel(tasks)

def multiArchFlow(String arch) {

    tech = "nodejs"

    stage('initial') {
        sh "echo ${configuration}"
    }

    println(configuration.contains("checkout"))
    if (configuration.contains("checkout")) {
        stage('checkout') {
            checkout(tech)
            sh "echo ${STAGE_NAME}"
        }
    }
    
    downloadTooling(tech)

    build(tech)
}