@Library('pipeline-library')

Map tasks = [failFast: false]

tech = "nodejs"

tasks["${LABEL_ARCH_X86}"] = { ->
    node() {
        multiArchFlow("${LABEL_ARCH_X86}")
    }
}
tasks["${LABEL_ARCH_ARM}"] = { ->
    node() {
        multiArchFlow("${LABEL_ARCH_ARM}")
    }
}

def multiArchFlow() {
    node {
        checkout(tech)
        
        downloadTooling(tech)

        build(tech)
    }
}