@Library('pipeline-library')

Map tasks = [failFast: false]

def configuration = [
    "checkout", "download_tooling"
]

tasks['x86'] = { ->
    node {
        multiArchFlow('x86')
    }
}
tasks['arm'] = { ->
    node {
        multiArchFlow('arm')
    }
}

// Run both task in parallel
parallel(tasks)

def multiArchFlow(String arch, configuration) {

    tech = "nodejs"

    stage('initial') {
        sh "echo ${configuration}"
    }

    checkout(tech)
    
    downloadTooling(tech)

    build(tech)
}